### ISSUE TITLE
通知メッセージ

### ISSUE THREAD

**Issue by cohakim** [cohakim/clean_them_all#108]
```
class NotificationMessage < ActiveHash::Base
  fields :id, :start, :finish

  # TODO: メッセージをファイルから読み込む

  def self.find_by_random
    all.sample
  end
end
```

```
ja:
  notifications:
    messages:
      link: '呪われしツイートを一括削除！ 黒歴史クリーナー - https://kurorekishi.me/cleaner #黒歴史クリーナー'
      body:
        cute_01:
          start: 'ツイ消ししちゃお ꉂꉂƱʊ꒰>ꈊ<ૢ꒱❣❣'
          finish: 'ツイ消ししちゃった ꒰ •ॢ ̫ -ॢ๑꒱✩ '
        cute_02:
          start: '｡ஐஃツイ消しནʓネヾ(öᴗ<๑)｡ஐஃ'
          finish: 'ツイ消ししたよ (◍⁃͈ᴗ•͈)४४४♡*'
        gross_01:
          start: 'ツイ消し中 (ꈨຶꎁꈨຶ)۶" ꁖʓ╵᷅ժ ̀꒭~ '
          finish: 'ツイ消し完了 (๑‾᷆д‾᷇๑)৳৸ᵃᵑᵏ Ꮍ৹੫ᵎ '
        gross_02:
          start: '(╭☞•́⍛•̀)╭☞ 今からツイ消ししまーっす'
          finish: 'ツイ消ししましたが、なにか？ ʕ •́؈•̀ ₎'
        cool_01:
          start: 'ツイ消しせねばっ =͟͟͞͞(๑•̀ㅁ•́ฅ✧'
          finish: 'ツイ消し終わった (๐ ́꒪̐ꈊ͒꒪̐)ꐳ'
        cool_02:
          start: 'ツイ消しにきました ʕ•̫͡•ʕ•̫͡•ʔ•̫͡•ʔ•̫͡•ʕ•̫͡•ʔ•̫͡•'
          finish: 'ツイ消し終わりましたー ʕु•̫͡•ʔु ✧'
        sadness_01:
          start: 'ツイ消しします (˚ ˃̣̣̥ω˂̣̣̥ )'
          finish: 'ツイ消ししましたっ ˚‧º·(˚ ˃̣̣̥⌓˂̣̣̥ )‧º·˚'
```
